### ISSUE TITLE
代码复现遇到的问题

### ISSUE THREAD

**Issue by 599020328** [yuyijie1995/2018-CCF-BDCI-ALIBABA-3Dpoint-cloud-segmentation#1]
我在代码复现时，运行到eval.py  第76行   boxes, probs, labels, *masks = model_func(resized_img)
时，输出一句check failed就退出了，没有抛出异常，请问有人知道是什么原因么？ 日志输出如下：
F d:\build\tensorflow\tensorflow-r1.9\tensorflow\core\kernels\mkl_avgpooling_op.cc:146] Check failed: dnnExecute_F32(mkl_context.prim_pooling_fwd, mkl_context.pooling_res) == E_SUCCESS (-1 vs. 0)
![Uploading image.png…]()

**Comment by atlascollege** [comment]
请问您的代码能够复现吗，我现在是遇到模型参数不能读入的问题

**Comment by 599020328** [comment]
不能
